$(document).on('click', '.dropdown-menu-monstro li a', function() {
     $(".btn-monstro:first-child").text($(this).text());
     $(".btn-monstro:first-child").val($(this).text());

     var spellName = $(".btn-monstro:first-child").val();
     // $( "#spell-list" ).load('spells/spells.html div[data-name="'+spellName+'"]');
});


$( document ).ready(function() {
  var monstrosVisiveis = monstros["Todos"];
  $.each(monstrosVisiveis, function(index, value) {
    // if (monstrosVisiveis[index][1] == nivelSelecionado) {
      $("#ULdropdownMonstro").append(
        "<li><a href=\"#\">"+monstrosVisiveis[index][0]+"</a></li>"
      );
    // }
  });
});




var monstros = {}

monstros["Todos"] = [
  ["Aarakocra","1/4","Médio","Humanoide","Não-Definida","Neutro","Bom"],
  ["Abocanhador Matraqueante","2","Médio","Aberração","Não-Definida","Neutro","Neutro"],
  ["Abolete","10","Grande","Aberração","Não-Definida","Leal","Mau"],
  ["Abutre","0","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Abutre Gigante","1","Grande","Besta","Criaturas Diversas","Neutro","Mal"],
  ["Acólito","1/4","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Águia","0","Pequeno","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Águia Gigante","1","Grande","Besta","Criaturas Diversas","Neutro","Bom"],
  ["Alce","1/4","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Alce gigante","2","Enorme","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Allossauro","2","Grande","Besta","Dinossauros","Nenhum","Nenhum"],
  ["Androesfinge","17","Grande","Monstruosidade","Esfinges","Leal","Neutro"],
  ["Animalia da Água","3","Grande","Elemental","Não-Definida","Neutro","Neutro"],
  ["Ankheg","2","Grande","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Anquilossauro","3","Enorme","Besta","Dinossauros","Nenhum","Nenhum"],
  ["Aparição","5","Médio","Morto-vivo","Não-Definida","Neutro","Mal"],
  ["Aranha","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Aranha gigante","1","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Aranha Interplanar","3","Grande","Monstruosidade","Criaturas Diversas","Nenhum","Nenhum"],
  ["Aranha-lobo gigante","1/4","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Arbusto Desperto","0","Pequeno","Planta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Arbusto Errante","5","Grande","Planta","Não-Definida","Nenhum","Nenhum"],
  ["Arcanaloth","12","Médio","Corruptor","Yugoloths","Neutro","Mal"],
  ["Arcano","6","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Armadura animada","1","Médio","Constructo","Objetos Animados","Nenhum","Nenhum"],
  ["Arminho","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Arminho gigante","1/4","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Arquimago","12","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Árvore Desperta","2","Enorme","Planta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Assassino","8","Médio","Humanoide","Personagens do Mestre","Qualquer","Não-Bom"],
  ["Azer","2","Médio","Elemental","Não-Definida","Leal","Neutro"],
  ["Babuíno","0","Pequeno","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Baleia Assassina","3","Enorme","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Balor","19","Enorme","Corruptor","Demônios","Caótico","Mau"],
  ["Bandido","1/8","Médio","Humanoide","Personagens do Mestre","Não-Leal","Qualquer"],
  ["Banshee","4","Médio","Morto-vivo","Não-Definida","Caótico","Mau"],
  ["Barão Sahuagin","5","Grande","Humanoide","Sahuagin","Leal","Mau"],
  ["Barlgura","5","Grande","Corruptor","Demônios","Caótico","Mau"],
  ["Basilisco","3","Médio","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Batedor","1/2","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Behir","11","Enorme","Monstruosidade","Não-Definida","Neutro","Mal"],
  ["Besouro De Fogo Gigante","0","Pequeno","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Bico de Machado","1/4","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Bidrone","1/4","Médio","Constructo","Modrons","Leal","Neutro"],
  ["Bode","0","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Bode gigante","1/2","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Bruxa da Noite","5","Médio","Corruptor","Bruxas","Neutro","Mal"],
  ["Bruxa da Noite (covil)","7","Médio","Corruptor","Bruxas","Neutro","Mal"],
  ["Bruxa do Mar","2","Médio","Fada","Bruxas","Caótico","Mau"],
  ["Bruxa do Mar (covil)","4","Médio","Fada","Bruxas","Caótico","Mau"],
  ["Bruxa Verde","3","Médio","Fada","Bruxas","Neutro","Mal"],
  ["Bruxa Verde (covil)","5","Médio","Fada","Bruxas","Neutro","Mal"],
  ["Bugbear","1","Médio","Humanoide","Bugbears","Caótico","Mau"],
  ["Bugbear Comandante","3","Médio","Humanoide","Bugbears","Caótico","Mau"],
  ["Bulette","5","Grande","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Bullywug","1/4","Médio","Humanoide","Não-Definida","Neutro","Mal"],
  ["Caçador Invisível","6","Médio","Elemental","Não-Definida","Neutro","Neutro"],
  ["Cambion","5","Médio","Corruptor","Não-Definida","Qualquer","Mau"],
  ["Camelo","1/8","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Cão da Morte","1","Médio","Monstruosidade","Criaturas Diversas","Neutro","Mal"],
  ["Cão Infernal","3","Médio","Corruptor","Não-Definida","Leal","Mau"],
  ["Cão Teleportador","1/4","Médio","Fada","Criaturas Diversas","Leal","Bom"],
  ["Capitão dos Bandidos","2","Médio","Humanoide","Personagens do Mestre","Não-Leal","Qualquer"],
  ["Capitão Hobgoblin","3","Médio","Humanoide","Hobgoblins","Leal","Mau"],
  ["Caranguejo","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Caranguejo Gigante","1/8","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Carniçal","1","Médio","Morto-vivo","Carniçais","Caótico","Mau"],
  ["Cavaleiro","3","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Cavaleiro da Morte","17","Médio","Morto-vivo","Não-Definida","Caótico","Mau"],
  ["Cavaleiro githyanki","8","Médio","Humanoide","Gith","Leal","Mau"],
  ["Cavalo de Carga","1/4","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Cavalo de Guerra","1/2","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Cavalo de Montaria","1/4","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Cavalo-Marinho","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Cavalo-marinho gigante","1/2","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Caveira Flamejante","4","Miúdo","Morto-vivo","Não-Definida","Neutro","Mal"],
  ["Centauro","2","Grande","Monstruosidade","Não-Definida","Neutro","Bom"],
  ["Centopéia Gigante","1/4","Pequeno","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Chacal","0","Pequeno","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Chasme","6","Grande","Corruptor","Demônios","Caótico","Mau"],
  ["Chefe Goblin","1","Pequeno","Humanoide","Goblins","Neutro","Mal"],
  ["Chuul","4","Grande","Aberração","Não-Definida","Caótico","Mau"],
  ["Ciclope","6","Enorme","Gigante","Não-Definida","Caótico","Neutro"],
  ["Cobra Constritora","1/4","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Cobra Constritora Gigante","2","Enorme","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Cobra Voadora","1/8","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Cocatriz","1/2","Pequeno","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Comandante de Guerra Orc","4","Médio","Humanoide","Orcs","Caótico","Mau"],
  ["Coruja","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Coruja gigante","1/4","Grande","Besta","Criaturas Diversas","Neutro","Neutro"],
  ["Corvo","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Couatl","4","Médio","Celestial","Não-Definida","Leal","Bom"],
  ["Cria Vampírica","5","Médio","Morto-vivo","Vampiros","Neutro","Mal"],
  ["Crocodilo","1/2","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Crocodilo gigante","5","Enorme","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Cubo Gelatinoso","2","Grande","Limo","Limos","Nenhum","Nenhum"],
  ["Cultista","1/8","Médio","Humanoide","Personagens do Mestre","Qualquer","Não-Bom"],
  ["Dao","11","Grande","Elemental","Gênios","Neutro","Mal"],
  ["Demilich","18","Miúdo","Morto-vivo","Não-Definida","Neutro","Mal"],
  ["Demilich (Acererak no covil)","23","Miúdo","Morto-vivo","Não-Definida","Neutro","Mal"],
  ["Demilich (Acererak)","21","Miúdo","Morto-vivo","Não-Definida","Neutro","Mal"],
  ["Demilich (covil)","20","Miúdo","Morto-vivo","Não-Definida","Neutro","Mal"],
  ["Demônio das Sombras","4","Médio","Corruptor","Demônios","Caótico","Mau"],
  ["Deva","10","Médio","Celestial","Anjos","Leal","Bom"],
  ["Devorador de Intelecto","2","Miúdo","Aberração","Não-Definida","Leal","Mau"],
  ["Devorador de Mentes","7","Médio","Aberração","Devorador de Mentes","Leal","Mau"],
  ["Devorador de Mentes Arcanista","8","Médio","Aberração","Devorador de Mentes","Leal","Mau"],
  ["Diabo Barbado","3","Médio","Corruptor","Diabos","Leal","Mau"],
  ["Diabo das Correntes","8","Médio","Corruptor","Diabos","Leal","Mau"],
  ["Diabo de Chifres","11","Grande","Corruptor","Diabos","Leal","Mau"],
  ["Diabo do Gelo","14","Grande","Corruptor","Diabos","Leal","Mau"],
  ["Diabo dos Espinhos","2","Pequeno","Corruptor","Diabos","Leal","Mau"],
  ["Diabo dos Ossos","9","Grande","Corruptor","Diabos","Leal","Mau"],
  ["Diabo Farpado","5","Médio","Corruptor","Diabos","Leal","Mau"],
  ["Diabrete","1","Miúdo","Corruptor","Diabos","Leal","Mau"],
  ["Djinni","11","Grande","Elemental","Gênios","Caótico","Bom"],
  ["Doninha","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Doninha Gigante","1/8","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Dracolich Azul Adulto","17","Enorme","Morto-vivo","Dracolich","Leal","Mau"],
  ["Dragão Azul Adulto","16","Enorme","Dragão","Dragões","Leal","Mau"],
  ["Dragão Azul Ancião","23","Imenso","Dragão","Dragões","Leal","Mau"],
  ["Dragão Azul Filhote","3","Médio","Dragão","Dragões","Leal","Mau"],
  ["Dragão Azul Jovem","9","Grande","Dragão","Dragões","Leal","Mau"],
  ["Dragão Branco Adulto","13","Enorme","Dragão","Dragões","Caótico","Mau"],
  ["Dragão Branco Ancião","20","Imenso","Dragão","Dragões","Caótico","Mau"],
  ["Dragão Branco Filhote","2","Médio","Dragão","Dragões","Caótico","Mau"],
  ["Dragão Branco Jovem","6","Grande","Dragão","Dragões","Caótico","Mau"],
  ["Dragão de Bronze Adulto","15","Enorme","Dragão","Dragões","Leal","Bom"],
  ["Dragão de Bronze Ancião","22","Imenso","Dragão","Dragões","Leal","Bom"],
  ["Dragão de Bronze Filhote","2","Médio","Dragão","Dragões","Leal","Bom"],
  ["Dragão de Bronze Jovem","8","Grande","Dragão","Dragões","Leal","Bom"],
  ["Dragão de cobre adulto","14","Enorme","Dragão","Dragões","Caótico","Bom"],
  ["Dragão de cobre Ancião","21","Imenso","Dragão","Dragões","Caótico","Bom"],
  ["Dragão de cobre Filhote","1","Médio","Dragão","Dragões","Caótico","Bom"],
  ["Dragão de cobre Jovem","7","Grande","Dragão","Dragões","Caótico","Bom"],
  ["Dragão de latão adulto","13","Enorme","Dragão","Dragões","Caótico","Bom"],
  ["Dragão de latão Ancião","20","Imenso","Dragão","Dragões","Caótico","Bom"],
  ["Dragão de latão Filhote","1","Médio","Dragão","Dragões","Caótico","Bom"],
  ["Dragão de latão Jovem","6","Grande","Dragão","Dragões","Caótico","Bom"],
  ["Dragão de ouro Adulto","17","Enorme","Dragão","Dragões","Leal","Bom"],
  ["Dragão de ouro Ancião","24","Imenso","Dragão","Dragões","Leal","Bom"],
  ["Dragão de ouro Filhote","3","Médio","Dragão","Dragões","Leal","Bom"],
  ["Dragão de ouro Jovem","10","Grande","Dragão","Dragões","Leal","Bom"],
  ["Dragão de Prata Adulto","16","Enorme","Dragão","Dragões","Leal","Bom"],
  ["Dragão de Prata Ancião","23","Imenso","Dragão","Dragões","Leal","Bom"],
  ["Dragão de Prata Filhote","2","Médio","Dragão","Dragões","Leal","Bom"],
  ["Dragão de Prata Jovem","9","Grande","Dragão","Dragões","Leal","Bom"],
  ["Dragão Negro Adulto","14","Enorme","Dragão","Dragões","Caótico","Mau"],
  ["Dragão Negro Ancião","21","Imenso","Dragão","Dragões","Caótico","Mau"],
  ["Dragão Negro Filhote","2","Médio","Dragão","Dragões","Caótico","Mau"],
  ["Dragão Negro Jovem","7","Grande","Dragão","Dragões","Caótico","Mau"],
  ["Dragão Verde Adulto","15","Enorme","Dragão","Dragões","Leal","Mau"],
  ["Dragão Verde Ancião","22","Imenso","Dragão","Dragões","Leal","Mau"],
  ["Dragão Verde Filhote","2","Médio","Dragão","Dragões","Leal","Mau"],
  ["Dragão Verde Jovem","8","Grande","Dragão","Dragões","Leal","Mau"],
  ["Dragão Vermelho Adulto","17","Enorme","Dragão","Dragões","Caótico","Mau"],
  ["Dragão Vermelho Ancião","24","Imenso","Dragão","Dragões","Caótico","Mau"],
  ["Dragão Vermelho das Sombras Jovem","13","Grande","Dragão","Dragon, Shadow","Caótico","Mau"],
  ["Dragão Vermelho Filhote","4","Médio","Dragão","Dragões","Caótico","Mau"],
  ["Dragão Vermelho Jovem","10","Grande","Dragão","Dragões","Caótico","Mau"],
  ["Dragão-fada (amarelo)","1","Miúdo","Dragão","Não-Definida","Caótico","Bom"],
  ["Dragão-fada (azul)","2","Miúdo","Dragão","Não-Definida","Caótico","Bom"],
  ["Dragão-fada (índigo)","2","Miúdo","Dragão","Não-Definida","Caótico","Bom"],
  ["Dragão-fada (laranja)","1","Miúdo","Dragão","Não-Definida","Caótico","Bom"],
  ["Dragão-fada (verde)","2","Miúdo","Dragão","Não-Definida","Caótico","Bom"],
  ["Dragão-fada (vermelho)","1","Miúdo","Dragão","Não-Definida","Caótico","Bom"],
  ["Dragão-fada (violeta)","2","Miúdo","Dragão","Não-Definida","Caótico","Bom"],
  ["Dretch","1/4","Pequeno","Corruptor","Demônios","Caótico","Mau"],
  ["Dríade","1","Médio","Fada","Não-Definida","Neutro","Neutro"],
  ["Drider","6","Grande","Monstruosidade","Não-Definida","Caótico","Mau"],
  ["Drow","1/4","Médio","Humanoide","Elfos: Drow","Neutro","Mal"],
  ["Drow Arcano","7","Médio","Humanoide","Elfos: Drow","Neutro","Mal"],
  ["Drow Guerreiro de Elite","5","Médio","Humanoide","Elfos: Drow","Neutro","Mal"],
  ["Drow Sacerdotiza de Lolth","8","Médio","Humanoide","Elfos: Drow","Neutro","Mal"],
  ["Druída","2","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Duergar","1","Médio","Humanoide","Não-Definida","Leal","Mau"],
  ["Duplo","3","Médio","Monstruosidade","Não-Definida","Neutro","Neutro"],
  ["Efreeti","11","Grande","Elemental","Gênios","Leal","Mau"],
  ["Elefante","4","Enorme","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Elemental da Água","5","Grande","Elemental","Elementais","Neutro","Neutro"],
  ["Elemental da Terra","5","Grande","Elemental","Elementais","Neutro","Neutro"],
  ["Elemental do Ar","5","Grande","Elemental","Elementais","Neutro","Neutro"],
  ["Elemental do Fogo","5","Grande","Elemental","Elementais","Neutro","Neutro"],
  ["Empírico","23","Enorme","Celestial","Não-Definida","Não-Leal","Não-Neutro"],
  ["Ente","9","Enorme","Planta","Não-Definida","Caótico","Bom"],
  ["Enxame de Corvos","1/4","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Enxame de Insetos","1/2","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Enxame de Morcegos","1/4","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Enxame de Piranhas","1","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Enxame de Ratos","1/4","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Enxame de Serpentes Venenosas","2","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Erínia","12","Médio","Corruptor","Diabos","Leal","Mau"],
  ["Escorpião","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Escorpião Gigante","3","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Espada Voadora","1/4","Pequeno","Constructo","Objetos Animados","Nenhum","Nenhum"],
  ["Espantalho","1","Médio","Constructo","Não-Definida","Caótico","Mau"],
  ["Espectador","3","Médio","Aberração","Observadores","Leal","Neutro"],
  ["Espectro","1","Médio","Morto-vivo","Espectro","Caótico","Mau"],
  ["Espeto Infectado","1/4","Médio","Planta","Blights","Neutro","Mal"],
  ["Espião","1","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Esporo de Gás","1/2","Grande","Planta","Fungos","Nenhum","Nenhum"],
  ["Esqueleto","1/4","Médio","Morto-vivo","Esqueletos","Leal","Mau"],
  ["Esqueleto de Cavalo de Guerra","1/2","Grande","Morto-vivo","Esqueletos","Leal","Mau"],
  ["Esqueleto de Minotauro","2","Grande","Morto-vivo","Esqueletos","Leal","Mau"],
  ["Estrangulador","5","Grande","Monstruosidade","Não-Definida","Neutro","Mal"],
  ["Ettercap","2","Médio","Monstruosidade","Não-Definida","Neutro","Mal"],
  ["Ettin","4","Grande","Gigante","Não-Definida","Caótico","Mau"],
  ["Falcão","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Falcão de Sangue","1/8","Pequeno","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Fanático do Culto","2","Médio","Humanoide","Personagens do Mestre","Qualquer","Não-Bom"],
  ["Fantasma","4","Médio","Morto-vivo","Não-Definida","Qualquer","Qualquer"],
  ["Flumph","1/8","Pequeno","Aberração","Não-Definida","Leal","Bom"],
  ["Fogo-Fátuo","2","Miúdo","Morto-vivo","Não-Definida","Caótico","Mau"],
  ["Fomori","8","Enorme","Gigante","Não-Definida","Caótico","Mau"],
  ["Fungo Violeta","1/4","Médio","Planta","Fungos","Nenhum","Nenhum"],
  ["Furioso","2","Médio","Humanoide","Personagens do Mestre","Caótico","Qualquer"],
  ["Galeb Duhr","6","Médio","Elemental","Não-Definida","Neutro","Neutro"],
  ["Galho Infectado","1/8","Pequeno","Planta","Blights","Neutro","Mal"],
  ["Gárgula","2","Médio","Elemental","Não-Definida","Caótico","Mau"],
  ["Garra Rastejante","0","Miúdo","Morto-vivo","Não-Definida","Neutro","Mal"],
  ["Gato","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Gigante da Colina","5","Enorme","Gigante","Gigantes","Caótico","Mau"],
  ["Gigante da Tempestade","13","Enorme","Gigante","Gigantes","Caótico","Bom"],
  ["Gigante das Nuvens","9","Enorme","Gigante","Gigantes","Neutro","Não-Neutro"],
  ["Gigante de Ferro","16","Grande","Constructo","Golens","Nenhum","Nenhum"],
  ["Gigante de Pedra","7","Enorme","Gigante","Gigantes","Neutro","Neutro"],
  ["Gigante do Fogo","9","Enorme","Gigante","Gigantes","Leal","Mau"],
  ["Gigante do Gelo","8","Enorme","Gigante","Gigantes","Neutro","Mal"],
  ["Ginoesfinge","11","Grande","Monstruosidade","Esfinges","Leal","Neutro"],
  ["Glabrezu","9","Grande","Corruptor","Demônios","Caótico","Mau"],
  ["Gladiador","5","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Gnoll","1/2","Médio","Humanoide","Gnolls","Caótico","Mau"],
  ["Gnoll Lider de Matilha","2","Médio","Humanoide","Gnolls","Caótico","Mau"],
  ["Gnoll Presa de Yeenoghu","4","Médio","Corruptor","Gnolls","Caótico","Mau"],
  ["Gnomo das Profundezas (Svirfneblin)","1/2","Pequeno","Humanoide","Gnomos, Profundezas (Svirfneblin)","Neutro","Bom"],
  ["Goblin","1/4","Pequeno","Humanoide","Goblins","Neutro","Mal"],
  ["Golem de Barro","9","Grande","Constructo","Golens","Nenhum","Nenhum"],
  ["Golem de Carne","5","Médio","Constructo","Golens","Nenhum","Nenhum"],
  ["Golem de pedra","10","Grande","Constructo","Golens","Nenhum","Nenhum"],
  ["Gorgon","5","Grande","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Gorila","1/2","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Gorila gigante","7","Enorme","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Goristro","17","Enorme","Corruptor","Demônios","Caótico","Mau"],
  ["Gosma Ocre","2","Grande","Limo","Limos","Nenhum","Nenhum"],
  ["Grell","3","Médio","Aberração","Não-Definida","Neutro","Mal"],
  ["Grick","2","Médio","Monstruosidade","Grick","Neutro","Neutro"],
  ["Grick Alpha","7","Grande","Monstruosidade","Grick","Neutro","Neutro"],
  ["Grifo","2","Grande","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Grimlock","1/4","Médio","Humanoide","Não-Definida","Neutro","Mal"],
  ["Guarda","1/8","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Guardião do Escudo","7","Grande","Constructo","Não-Definida","Nenhum","Nenhum"],
  ["Guerreiro Githyanki","3","Médio","Humanoide","Gith","Leal","Mau"],
  ["Guerreiro Tribal","1/8","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Guinchador","0","Médio","Planta","Fungos","Nenhum","Nenhum"],
  ["Harpia","1","Médio","Monstruosidade","Não-Definida","Caótico","Mau"],
  ["Hezrou","8","Grande","Corruptor","Demônios","Caótico","Mau"],
  ["Hidra","8","Enorme","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Hiena","0","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Hiena Gigante","1","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Hipogrifo","1","Grande","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Hobgoblin","1/2","Médio","Humanoide","Hobgoblins","Leal","Mau"],
  ["Hobgoblin Senhor da Guerra","6","Médio","Humanoide","Hobgoblins","Leal","Mau"],
  ["Homem-Chacal","1/2","Médio","Humanoide","Não-Definida","Caótico","Mau"],
  ["Homem-Javali","4","Médio","Humanoide","Licantropos","Neutro","Mal"],
  ["Homem-Rato","2","Médio","Humanoide","Licantropos","Leal","Mau"],
  ["Homem-Tigre","4","Médio","Humanoide","Licantropos","Neutro","Neutro"],
  ["Homem-Urso","5","Médio","Humanoide","Licantropos","Neutro","Bom"],
  ["Homúnculo","0","Miúdo","Constructo","Não-Definida","Neutro","Neutro"],
  ["Horror de Elmo","4","Médio","Constructo","Não-Definida","Neutro","Neutro"],
  ["Horror de Gancho","3","Grande","Monstruosidade","Não-Definida","Neutro","Neutro"],
  ["Inumano","3","Médio","Morto-vivo","Não-Definida","Neutro","Mal"],
  ["Javali","1/4","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Javali Gigante","2","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Kenku","1/4","Médio","Humanoide","Não-Definida","Caótico","Neutro"],
  ["Kobold","1/8","Pequeno","Humanoide","Kobolds","Leal","Mau"],
  ["Kobold Alado","1/4","Pequeno","Humanoide","Kobolds","Leal","Mau"],
  ["Kraken","23","Imenso","Monstruosidade","Não-Definida","Caótico","Mau"],
  ["Kuo-toa","1/4","Médio","Humanoide","Kuo-toa","Neutro","Mal"],
  ["Kuo-toa Açoitador","1","Médio","Humanoide","Kuo-toa","Neutro","Mal"],
  ["Kuo-toa Arcebispo","6","Médio","Humanoide","Kuo-toa","Neutro","Mal"],
  ["Kuo-toa Monitor","3","Médio","Humanoide","Kuo-toa","Neutro","Mal"],
  ["Lagarto","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Lagarto gigante","1/4","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Lâmia","4","Grande","Monstruosidade","Não-Definida","Caótico","Mau"],
  ["Larva Slaad","1/8","Miúdo","Aberração","Slaadi","Caótico","Neutro"],
  ["Leão","1","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Lêmure","0","Médio","Corruptor","Diabos","Leal","Mau"],
  ["Lich","21","Médio","Morto-vivo","Não-Definida","Qualquer","Mau"],
  ["Lich (covil)","22","Médio","Morto-vivo","Não-Definida","Qualquer","Mau"],
  ["Limo Cinzento","1/2","Médio","Limo","Limos","Nenhum","Nenhum"],
  ["Lívido","2","Médio","Morto-vivo","Carniçais","Caótico","Mau"],
  ["Lobisomem","3","Médio","Humanoide","Licantropos","Caótico","Mau"],
  ["Lobo","1/4","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Lobo Atroz","1","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Lobo Invernal","3","Grande","Monstruosidade","Criaturas Diversas","Neutro","Mal"],
  ["Magmin","1/2","Pequeno","Elemental","Não-Definida","Caótico","Neutro"],
  ["Mamute","6","Enorme","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Manes","1/8","Pequeno","Corruptor","Demônios","Caótico","Mau"],
  ["Manticora","3","Grande","Monstruosidade","Não-Definida","Leal","Mau"],
  ["Manto Negro","1/2","Pequeno","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Mantor","8","Grande","Aberração","Não-Definida","Caótico","Neutro"],
  ["Marid","11","Grande","Elemental","Gênios","Caótico","Neutro"],
  ["Marilith","16","Grande","Corruptor","Demônios","Caótico","Mau"],
  ["Mastim","1/8","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Medusa","6","Médio","Monstruosidade","Não-Definida","Leal","Mau"],
  ["Meio-Dragão Vermelho Veterano","5","Médio","Humanoide","Meio-Dragão","Qualquer","Qualquer"],
  ["Meio-Ogro","1","Grande","Gigante","Ogros","Caótico","Mau"],
  ["Mephit da Fumaça","1/4","Pequeno","Elemental","Mephits","Neutro","Mal"],
  ["Mephit da Lama","1/4","Pequeno","Elemental","Mephits","Neutro","Mal"],
  ["Mephit da Poeira","1/2","Pequeno","Elemental","Mephits","Neutro","Mal"],
  ["Mephit do Gelo","1/2","Pequeno","Elemental","Mephits","Neutro","Mal"],
  ["Mephit do Magma","1/2","Pequeno","Elemental","Mephits","Neutro","Mal"],
  ["Mephit do Vapor","1/4","Pequeno","Elemental","Mephits","Neutro","Mal"],
  ["Mezzoloth","5","Médio","Corruptor","Yugoloths","Neutro","Mal"],
  ["Miconide Adulto","1/2","Médio","Planta","Miconides","Leal","Neutro"],
  ["Miconide Broto","0","Pequeno","Planta","Miconides","Leal","Neutro"],
  ["Miconide Soberano","2","Grande","Planta","Miconides","Leal","Neutro"],
  ["Mímico","2","Médio","Monstruosidade","Não-Definida","Neutro","Neutro"],
  ["Minotauro","3","Grande","Monstruosidade","Não-Definida","Caótico","Mau"],
  ["Monge Githzerai","2","Médio","Humanoide","Gith","Leal","Neutro"],
  ["Monodrone","1/8","Médio","Constructo","Modrons","Leal","Neutro"],
  ["Monstro da Ferrugem","1/2","Médio","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Morcego","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Morcego gigante","1/4","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Mula","1/8","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Múmia","3","Médio","Morto-vivo","Múmias","Leal","Mau"],
  ["Naga dos Ossos","4","Grande","Morto-vivo","Nagas","Leal","Mau"],
  ["Naga Espiritual","8","Grande","Monstruosidade","Nagas","Caótico","Mau"],
  ["Naga Guardiã","10","Grande","Monstruosidade","Nagas","Leal","Bom"],
  ["Nalfeshnee","13","Grande","Corruptor","Demônios","Caótico","Mau"],
  ["Nobre","1/8","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Nótico","2","Médio","Aberração","Não-Definida","Neutro","Mal"],
  ["Nycaloth","9","Grande","Corruptor","Yugoloths","Neutro","Mal"],
  ["Observador","13","Grande","Aberração","Observadores","Leal","Mau"],
  ["Observador (covil)","14","Grande","Aberração","Observadores","Leal","Mau"],
  ["Observador Zumbi","5","Grande","Morto-vivo","Zumbis","Neutro","Mal"],
  ["Ogro","2","Grande","Gigante","Ogros","Caótico","Mau"],
  ["Ogro Zumbi","2","Grande","Morto-vivo","Zumbis","Neutro","Mal"],
  ["Oni","7","Grande","Gigante","Não-Definida","Leal","Mau"],
  ["Orc","1/2","Médio","Humanoide","Orcs","Caótico","Mau"],
  ["Orc Olho de Gruumsh","2","Médio","Humanoide","Orcs","Caótico","Mau"],
  ["Orog","2","Médio","Humanoide","Orcs","Caótico","Mau"],
  ["Otyugh","5","Grande","Aberração","Não-Definida","Neutro","Neutro"],
  ["Pantera","1/4","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Pantera Deslocadora","3","Grande","Monstruosidade","Não-Definida","Leal","Mau"],
  ["Pégaso","2","Grande","Celestial","Não-Definida","Caótico","Bom"],
  ["Pentadrone","2","Grande","Constructo","Modrons","Leal","Neutro"],
  ["Perfurador","1/2","Médio","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Peryton","2","Grande","Monstruosidade","Não-Definida","Caótico","Mau"],
  ["Pesadelo","3","Grande","Corruptor","Não-Definida","Neutro","Mal"],
  ["Piranha","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Pixie","1/4","Miúdo","Fada","Não-Definida","Neutro","Bom"],
  ["Planetário","16","Grande","Celestial","Anjos","Leal","Bom"],
  ["Plebeu","0","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Plesiossauro","2","Grande","Besta","Dinossauros","Nenhum","Nenhum"],
  ["Poltergeist","2","Médio","Morto-vivo","Espectro","Caótico","Mau"],
  ["Polvo","0","Pequeno","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Polvo Gigante","1","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Ponei","1/8","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Povo do Mar","1/8","Médio","Humanoide","Não-Definida","Neutro","Neutro"],
  ["Povo Lagarto","1/2","Médio","Humanoide","Povo Lagarto","Neutro","Neutro"],
  ["Pseudodragão","1/4","Miúdo","Dragão","Não-Definida","Neutro","Bom"],
  ["Pteranodonte","1/4","Médio","Besta","Dinossauros","Nenhum","Nenhum"],
  ["Pudim Negro","4","Grande","Limo","Limos","Nenhum","Nenhum"],
  ["Quadrone","1","Médio","Constructo","Modrons","Leal","Neutro"],
  ["Quaggoth","2","Médio","Humanoide","Quaggoth","Caótico","Neutro"],
  ["Quaggoth Thonot","3","Médio","Humanoide","Quaggoth","Caótico","Neutro"],
  ["Quasit","1","Miúdo","Corruptor","Demônios","Caótico","Mau"],
  ["Quimera","6","Grande","Monstruosidade","Não-Definida","Caótico","Mau"],
  ["Rã gigante","1/4","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Rakshasa","13","Médio","Corruptor","Não-Definida","Leal","Mau"],
  ["Rato","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Rato Gigante","1/8","Pequeno","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Rei/Rainha do Povo Lagarto","4","Médio","Humanoide","Povo Lagarto","Caótico","Mau"],
  ["Remorhaz","11","Enorme","Monstruosidade","Remorhazes","Nenhum","Nenhum"],
  ["Remorhaz Jovem","5","Grande","Monstruosidade","Remorhazes","Nenhum","Nenhum"],
  ["Ressurgido","6","Médio","Morto-vivo","Não-Definida","Neutro","Neutro"],
  ["Rinoceronte","2","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Roca","11","Imenso","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Rufião","1/2","Médio","Humanoide","Personagens do Mestre","Qualquer","Não-Bom"],
  ["Sacerdote","2","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Sacerdotisa Sahuagin","2","Médio","Humanoide","Sahuagin","Leal","Mau"],
  ["Sahuagin","1/2","Médio","Humanoide","Sahuagin","Leal","Mau"],
  ["Salamandra","5","Grande","Elemental","Salamandras","Neutro","Mal"],
  ["Sapo","0","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Sapo gigante","1","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Sátiro","1/2","Médio","Fada","Não-Definida","Caótico","Neutro"],
  ["Senhor das Múmias","15","Médio","Morto-vivo","Múmias","Leal","Mau"],
  ["Senhor das Profundezas","20","Grande","Corruptor","Diabos","Leal","Mau"],
  ["Serpente de Fogo","1","Médio","Elemental","Salamandras","Neutro","Mal"],
  ["Serpente venenosa","1/8","Miúdo","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Serpente venenosa gigante","1/4","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Servo Esporo Quaggoth","1","Médio","Planta","Miconides","Nenhum","Nenhum"],
  ["Sirenídeo","2","Grande","Monstruosidade","Não-Definida","Caótico","Mau"],
  ["Slaad Azul","7","Grande","Aberração","Slaadi","Caótico","Neutro"],
  ["Slaad Cinza","9","Médio","Aberração","Slaadi","Caótico","Neutro"],
  ["Slaad da Morte","10","Médio","Aberração","Slaadi","Caótico","Mau"],
  ["Slaad Verde","8","Grande","Aberração","Slaadi","Caótico","Neutro"],
  ["Slaad Vermelho","5","Grande","Aberração","Slaadi","Caótico","Neutro"],
  ["Solar","21","Grande","Celestial","Anjos","Leal","Bom"],
  ["Sombra","1/2","Médio","Morto-vivo","Não-Definida","Caótico","Mau"],
  ["Sprite","1/4","Miúdo","Fada","Não-Definida","Neutro","Bom"],
  ["Stirge","1/8","Miúdo","Besta","Não-Definida","Nenhum","Nenhum"],
  ["Súcubo/Íncubo","4","Médio","Corruptor","Não-Definida","Neutro","Mal"],
  ["Tapete sufocador","2","Grande","Constructo","Objetos Animados","Nenhum","Nenhum"],
  ["Tarrasque","30","Imenso","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Tartaruga Dragão","17","Imenso","Dragão","Não-Definida","Neutro","Neutro"],
  ["Thri-kreen","1","Médio","Humanoide","Não-Definida","Caótico","Neutro"],
  ["Tigre","1","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Tigre Dentes-de-sabre","2","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Tirano da morte","14","Grande","Morto-vivo","Observadores","Leal","Mau"],
  ["Tirano da morte (covil)","15","Grande","Morto-vivo","Observadores","Leal","Mau"],
  ["Tiranossauro","8","Enorme","Besta","Dinossauros","Nenhum","Nenhum"],
  ["Tríbulo Brutal","5","Grande","Monstruosidade","Não-Definida","Caótico","Mau"],
  ["Tricerátops","5","Enorme","Besta","Dinossauros","Nenhum","Nenhum"],
  ["Tridrone","1/2","Médio","Constructo","Modrons","Leal","Neutro"],
  ["Troglodita","1/4","Médio","Humanoide","Não-Definida","Caótico","Mau"],
  ["Troll","5","Grande","Gigante","Não-Definida","Caótico","Mau"],
  ["Tubarão caçador","2","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Tubarão dos Arrecifes","1/2","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Tubarão gigante","5","Enorme","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Ultroloth","13","Médio","Corruptor","Yugoloths","Neutro","Mal"],
  ["Unicórnio","5","Grande","Celestial","Não-Definida","Leal","Bom"],
  ["Urso Marrom","1","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Urso Negro","1/2","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Urso Polar","2","Grande","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Urso-Coruja","3","Grande","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Vampiro","13","Médio","Morto-vivo","Vampiros","Leal","Mau"],
  ["Vampiro Conjurador","15","Médio","Morto-vivo","Vampiros","Leal","Mau"],
  ["Vampiro Guerreiro","15","Médio","Morto-vivo","Vampiros","Leal","Mau"],
  ["Veado","0","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Verme da Carniça","2","Grande","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Verme Púrpura","15","Imenso","Monstruosidade","Não-Definida","Nenhum","Nenhum"],
  ["Vespa Gigante","1/2","Médio","Besta","Criaturas Diversas","Nenhum","Nenhum"],
  ["Veterano","3","Médio","Humanoide","Personagens do Mestre","Qualquer","Qualquer"],
  ["Vinha Infectada","1/2","Médio","Planta","Blights","Neutro","Mal"],
  ["Vrock","6","Grande","Corruptor","Demônios","Caótico","Mau"],
  ["Worg","1/2","Grande","Monstruosidade","Criaturas Diversas","Neutro","Mal"],
  ["Wyvern","6","Grande","Dragão","Não-Definida","Nenhum","Nenhum"],
  ["Xamã do Povo Lagarto","2","Médio","Humanoide","Povo Lagarto","Neutro","Neutro"],
  ["Xorn","5","Médio","Elemental","Não-Definida","Neutro","Neutro"],
  ["Yeti","3","Grande","Monstruosidade","Yeti","Caótico","Mau"],
  ["Yeti Abominável","9","Enorme","Monstruosidade","Yeti","Caótico","Mau"],
  ["Yochlol","10","Médio","Corruptor","Demônios","Caótico","Mau"],
  ["Yuan-ti Abominação","7","Grande","Monstruosidade","Yuan-ti","Neutro","Mal"],
  ["Yuan-ti Mestiço","3","Médio","Monstruosidade","Yuan-ti","Neutro","Mal"],
  ["Yuan-ti Puro-Sangue","1","Médio","Humanoide","Yuan-ti","Neutro","Mal"],
  ["Zerth Githzerai","6","Médio","Humanoide","Gith","Leal","Neutro"],
  ["Zumbi","1/4","Médio","Morto-vivo","Zumbis","Neutro","Mal"]
];
// ["ataque certeiro","0"],
// ["consertar","0"],
// ["globos de luz","0"],
// ["ilusão menor","0"],
// ["mãos mágicas","0"],
// ["mensagem","0"],
// ["prestidigitação","0"],
// ["proteção contra lâminas","0"],
// ["zombaria viciosa","0"],
