//[ID DO PLAYER, RAÇA, ALINHAMENTO, ANTECENDENTES, CLASSE BASE, NIVEL CLASSE BASE, MULTICLASSE 1, NIVEL MULTICLASSE 1,
  // MULTICLASSE 2, NIVEL MULTICLASSE 2, XP DO PLAYER, FOR, DES, CON, SAB, CAR, INT, HP DISPONIVEL, TRACOS DE PERSONALIDADE, IDEAIS,
  // LIGACOES, DEFEITOS, ATAQUES E MAGIAS, CARACTERISTICAS E HABILIDADES, EQUIPAMENTOS E NOTAS]


//Lista de Players

var listaDePlayers = {};
var listaDeMagias = {};
var listaDePericias = {};
var listaDeProeficiencias = {};
var listaDeItens = {};


listaDePlayers["Campanha1"] = [
];

listaDeMagias["Campanha1"] = [
  //[ID DO PLAYER, NUMERO DE MAGIAS SELECIONADAS (X), NOME MAGIA 1, NOME MAGIA 2, NOME MAGIA ..., NOME MAGIA X, ]
];
listaDePericias["Campanha1"] = [
  //[ID DO PLAYER, NUMERO DE MAGIAS SELECIONADAS (X), NOME MAGIA 1, NOME MAGIA 2, NOME MAGIA ..., NOME MAGIA X, ]
];
listaDeProeficiencias["Campanha1"] = [
  //[ID DO PLAYER, NUMERO DE MAGIAS SELECIONADAS (X), NOME MAGIA 1, NOME MAGIA 2, NOME MAGIA ..., NOME MAGIA X, ]
];
listaDeItens["Campanha1"] = [
  //[ID DO PLAYER, NUMERO DE ITENS SELECIONADOS (X), NOME ITENS 1, NOME ITENS 2, NOME ITENS ..., NOME ITENS X, ]
];
